### ISSUE TITLE
Shortening link already shorten

### ISSUE THREAD

**Issue by rawasaditya** [ScriptRaccoon/svt.ink#1]
If product create short link, this same short link should not be processed again
for example if I shorten htttpa://www.google.com to https://svt.ink/rC8KKl then "https://svt.ink/rC8KKl" short not be shortened again.
I tried creating chain of these links and the used latest link to visit website it was not good experience

**Comment by ScriptRaccoon** [comment]
Thanks for this suggestion! This is a very good idea.
This should be fixed with [this commit](https://github.com/ScriptRaccoon/svt.ink/commit/31d656f88c6bffb3ec4737c9cfe2910a2184ba3a).
Can you please verify that the issue is gone?

**Comment by rawasaditya** [comment]
Great! Fixed
